---

configure_dnf: true
configure_zsh: true
configure_terminal: true

#DNF Configuration 
rpm_free_repo: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
rpm_nonfree_repo:   https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
gstream_plugin:
  - gstreamer1-libav
  - gstreamer1-plugin-openh264
  - gstreamer1-plugins-bad-free-extras
  - gstreamer1-plugins-bad-free-fluidsynth
  - gstreamer1-plugins-bad-free-wildmidi
  - gstreamer1-plugins-bad-free-zbar
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-good-extras

lame: lame-3.100-12.fc36.x86_64

multimedia_group:
  - gstreamer1-plugins-ugly
  - pipewire-codec-aptx

enable_third_party: fedora-workstation-repositories

vscode: https://packages.microsoft.com/keys/microsoft.asc
vscode_repo: sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

sublimetext3: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
sublimetext3_repo: sudo dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo

dnf_packages: 
  - google-chrome-stable
  - sublime-text
  - code
  - lpf-spotify-client
  - gnome-tweaks


#Termainl Configuration
terminal_packages:
  - zsh
  - starship
  - tmux
  - util-linux-user #For Changing ZSH SHELL AS DEFAULT

#dotfiles config
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .zshrc
dotfiles_folder:
  - starship.toml
  - tmux

